### ISSUE TITLE
Push Requests

### ISSUE THREAD

**Issue by splitice** [rmarx/quicker#4]
We are currently looking for a UDP protocol capable of server side initialized sessions (i.e server push). I know HTTP/2 that runs on QUIC supports this, so QUIC must be capable of it too.

Googles quic documentation states "Streams can be created either by the client or the server". Currently I can't see this implemented with this library. Could it be?

**Comment by rmarx** [comment]
Hello Matthew,

QUIC has the concept of server-initiated streams, both unidirectional (client cannot answer on the same stream, e.g., [a typical HTTP/2 push stream](https://tools.ietf.org/html/draft-ietf-quic-http-13#section-3.3.2)) and bidirectional (full duplex). The definitions for these can be found in src/quicker/stream.ts and a stream of that type is created in src/quicker/stream.manager.ts:getNextStream. While this *should* work, be aware that we currently have no automated test suite covering quicker and have not exhaustively tested server-initiated streams.

At risk of telling you what you already know (and for other people new to this topic), be aware that server-initialized **streams** are not server-initialized **sessions/connections**. QUIC still requires the client to make the first connection to the server (or a reachable peer) before the server can "push" resources. The server is unable to push to the client without an existing connection having been setup first. This is true for almost all protocols, given things like NAT and firewalls. If you really need fully server-initialized messages, look into how Google handles Push Notifications on Android for example. 

Please let me know if this was clear and if I can close the issue.

**Comment by splitice** [comment]
Yes this makes sense, I can see now that getNextStream should do the job.

Thanks.
