### ISSUE TITLE
Add version-related transport parameters

### ISSUE THREAD

**Issue by rmarx** [rmarx/quicker#5]
Currently, we don't use the QUIC version-related information in the transport parameters, which is needed to have session resumption work well in combination with version negotiation. 

See src/crypto/qtls.ts (generateExtensionData does add them, but we don't use them yet for selecting the correct QUIC version when resuming)

**Comment by kevin-kp** [comment]
should be fixed with #6 
version is kept in transport parameters and is chosen when session resumption is used instead of the regular getActiveVersion function
