### ISSUE TITLE
Peers seem to start ping ponging ACKs when sending big file

### ISSUE THREAD

**Issue by SvenT-1643710** [rmarx/quicker#68]
When a big file is sent, two peers seem to start ping ponging ACKs back and forth.
There are also some STREAM_BLOCKED frames that get sent in this situation.  

The ping ponging does end after some time

**Comment by rmarx** [comment]
A few more observations:
- the measured RTTs here were also very high (+5s) so it's logical that there are a lot of outstanding and duplicated ACKs
- However, we should check if the ping-ponging is expected and that is was actually ping-ponging and not just a by-product of the very high RTT interacting with the ACK alarm.

**Comment by rmarx** [comment]
They were not ping-ponging, everything was just too slow to keep up.
